<span class="thrive-page-template-icon">
	<#= TVE.icon( 'template-settings-page', 'svg', '', this.model.get('extra_classes') ) #>
</span>
<div class="thrive-page-template-cell">
	<span class="thrive-page-template-title"><#= this.model.get('name') #></span>
	<span class="thrive-page-template-subtitle"><#= this.model.get('type_label') #></span>
</div>
<button class="thrive-page-template-activate click" data-fn="activateTemplate">
	<span class="thrive-page-template-inactive-text">
			<?php echo __( 'Activate', THEME_DOMAIN ); ?>
	</span>
	<span class="thrive-page-template-active-text">
			<?php echo __( 'Active', THEME_DOMAIN ); ?>
	</span>
</button>
<# if ( this.model.isDefault() && this.model.isCurrentPostFormat() && !this.model.get( 'selected' ) ) { #>
<span class="tpt-default-text is-default">
		<?php echo __( 'Default', THEME_DOMAIN ); ?>
</span>
<# } #>

