<div class="woo-product-notice">
	<p><strong>WooCommerce Compatibility is Currently in Beta</strong></p>
	<p>We are currently working on bringing an exciting WooCommerce shop building experience to Thrive Theme Builder.</p>
	<p>Some of the WooCommerce functionality has been completed so that you can experiment with it but please don't use the WooCommerce functionality on a production site at this point.</p>
	<p>We aim to fully complete our WooCommerce integration by the end of May. If you'd like to be notified when this happens then
		<a href="https://thrivethemes.com/woocommerce-waitlist/" target="_blank">sign up to our notification list</a>.
	</p>
</div>
